name: 🚀 Deploy website on push
on:
  push:
   branches: main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.cluster029.hosting.ovh.net
        username: ${{ secrets.OVH_ID }}
        password: ${{ secrets.OVH_PASSWORD }}
        server-dir: './www/'
        exclude: |
          **/.git*
          **/.git*/**
          **.gitignore
          **/README.md
          **/apercu-portfolio-2024-02.webp
          **/.vscode/
          **/.vscode/**
          **/.github/
          **/.github/**