name: 🚀 Deploy website on push
on:
  push:
   branches: dev-v2023
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4.1.1
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 185.171.202.140
        username: github
        password: ${{ secrets.PASSWORD }}